apiVersion: v1
kind: Service
metadata:
   labels:
     app: result-app
     name: result-service
spec:
 type: NodePort
 ports:
  - targetPort: 80
    port: 80
    nodePort: 30002
 selector: 
   name: result-pod